source 'http://rubygems.org'

gem 'puma'
gem 'rake', '~> 10.3'

gem 'sinatra', '~> 2.0.3'
gem 'sinatra-contrib'
gem 'faraday'
gem 'vcr', '~> 4.0'
gem 'json'
gem 'rack-parser', :require => 'rack/parser'

group :development, :test do
  gem 'byebug'
  gem 'guard-rspec', require: false
  gem 'webmock'
end

group :test do
  gem 'ruby-prof'
  gem 'factory_girl', '4.3.0'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers'
  gem 'simplecov', :require => false
end